'use client';
import { useEffect,useMemo,useState } from 'react';
import { ArrowLeft,ArrowUpRight,BriefcaseBusiness,Building2,CalendarDays,MapPin,Search,SlidersHorizontal,WalletCards,X } from 'lucide-react';
import { sampleJobs,type Job } from '@/lib/jobs';
const clean=(v:string)=>!v||v==='Não informado'?'Não informado':v;
const when=(value:string)=>{
 if(!value)return 'Recente';
 const text=String(value).trim();
 let date:Date;
 const iso=text.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);
 const br=text.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/);
 if(iso)date=new Date(Number(iso[1]),Number(iso[2])-1,Number(iso[3]),12);
 else if(br)date=new Date(Number(br[3]),Number(br[2])-1,Number(br[1]),12);
 else date=new Date(text);
 return Number.isNaN(date.getTime())?'Recente':new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(date);
};
export function JobBoard(){const[jobs,setJobs]=useState(sampleJobs),[query,setQuery]=useState(''),[area,setArea]=useState('Todas'),[model,setModel]=useState('Todos'),[location,setLocation]=useState('Todos'),[selected,setSelected]=useState<Job|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/jobs').then(r=>{if(!r.ok)throw new Error('Falha ao carregar vagas');return r.json()}).then(d=>setJobs(Array.isArray(d.jobs)&&d.jobs.length?d.jobs:sampleJobs)).catch(()=>setJobs(sampleJobs)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{document.body.style.overflow=selected?'hidden':'';return()=>{document.body.style.overflow=''}},[selected]);
 const opts=(key:'area'|'model'|'location')=>['Todos',...Array.from(new Set(jobs.map(j=>clean(j[key])).filter(v=>v!=='Não informado'))).sort()],areas=['Todas',...Array.from(new Set(jobs.map(j=>clean(j.area)).filter(v=>v!=='Não informado'))).sort()];
 const filtered=useMemo(()=>jobs.filter(j=>`${j.title} ${j.company} ${j.area} ${j.location}`.toLowerCase().includes(query.toLowerCase())&&(area==='Todas'||j.area===area)&&(model==='Todos'||clean(j.model)===model)&&(location==='Todos'||clean(j.location)===location)),[jobs,query,area,model,location]);
 return <main className="min-h-screen bg-[#f7f8f4] text-[#14231d]"><header className="border-b border-[#dfe5dc]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><a href="#vagas" className="flex items-center gap-3 font-semibold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#173f35] text-[#d7ff73]"><BriefcaseBusiness size={19}/></span>Grupo VIP <em className="-ml-2 not-italic text-[#3d6b5c]">Vagas</em></a><span className="hidden rounded-full border border-[#cfdacf] bg-white px-4 py-2 text-xs font-semibold text-[#4f665d] sm:block">Curadoria de Marketing Digital</span></div></header>
 <section className="border-b border-[#dfe5dc] bg-[#173f35] text-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 lg:grid-cols-[1fr_380px] lg:px-8 lg:py-16"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-[#d7ff73]">Oportunidades selecionadas</p><h1 className="max-w-3xl text-4xl font-semibold leading-[1.06] tracking-[-.04em] sm:text-6xl">Seu próximo passo no marketing pode estar aqui.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#c7d8d2] sm:text-lg">Vagas novas, verificadas e organizadas para você encontrar a oportunidade certa sem perder horas procurando.</p></div><div className="self-end rounded-3xl border border-white/15 bg-white/8 p-6"><p className="text-5xl font-semibold text-[#d7ff73]">{loading?'—':jobs.length}</p><p className="mt-2 text-sm text-[#c7d8d2]">vagas abertas agora</p><div className="mt-6 flex items-center gap-2 border-t border-white/15 pt-4 text-xs text-[#9db8ae]"><span className="h-2 w-2 rounded-full bg-[#d7ff73]"/>Atualizadas automaticamente</div></div></div></section>
 <section id="vagas" className="mx-auto max-w-7xl px-5 py-8 lg:px-8 lg:py-12"><div className="rounded-3xl border border-[#dfe5dc] bg-white p-5 shadow-[0_18px_50px_rgba(20,35,29,.05)]"><label className="flex items-center gap-3 border-b border-[#e6ebe4] pb-4"><Search size={20} className="text-[#688078]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque por cargo, empresa, área ou cidade" className="w-full bg-transparent outline-none" aria-label="Buscar vagas"/></label><div className="grid gap-3 pt-4 sm:grid-cols-3"><Filter label="Área" value={area} onChange={setArea} options={areas}/><Filter label="Modelo" value={model} onChange={setModel} options={opts('model')}/><Filter label="Local" value={location} onChange={setLocation} options={opts('location')}/></div></div>
 <div className="mt-8 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#648075]">Vagas abertas</p><h2 className="mt-1 text-2xl font-semibold">{filtered.length} oportunidades encontradas</h2></div>{(query||area!=='Todas'||model!=='Todos'||location!=='Todos')&&<button onClick={()=>{setQuery('');setArea('Todas');setModel('Todos');setLocation('Todos')}} className="text-sm font-semibold text-[#356d5b]">Limpar filtros</button>}</div><div className="mt-5 grid gap-4 lg:grid-cols-2">{filtered.map(j=><Card key={j.id} job={j} open={()=>setSelected(j)}/>)}</div>{!filtered.length&&<div className="mt-5 rounded-3xl border border-dashed border-[#bdcbbf] bg-white px-6 py-16 text-center"><SlidersHorizontal className="mx-auto"/><h3 className="mt-4 text-xl font-semibold">Nenhuma vaga com esses filtros</h3></div>}</section>
 <footer className="border-t border-[#dfe5dc] px-5 py-8 text-center text-sm text-[#687a73]">Grupo VIP Vagas · Curadoria humana para carreiras em Marketing Digital.</footer>{selected&&<Detail job={selected} close={()=>setSelected(null)}/>}</main>}
function Filter({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="flex flex-col gap-1"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-[#75877f]">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-[#dfe5dc] bg-[#f8faf7] px-3 py-2.5 text-sm font-medium">{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Card({job,open}:{job:Job;open:()=>void}){return <article className="flex flex-col rounded-3xl border border-[#dfe5dc] bg-white p-6 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#edf2ec] font-semibold text-[#365d50]">{job.company[0]}</div><span className="h-fit rounded-full bg-[#eff6dc] px-3 py-1 text-[11px] font-bold text-[#476020]">Candidatura aberta</span></div><p className="mt-5 text-sm font-semibold text-[#557168]">{job.company}</p><h3 className="mt-1 text-xl font-semibold leading-snug">{job.title}</h3><div className="mt-5 flex flex-wrap gap-2 text-xs font-medium text-[#53665e]"><Tag icon={<BriefcaseBusiness size={13}/>} text={clean(job.model)}/><Tag icon={<MapPin size={13}/>} text={clean(job.location)}/><Tag icon={<WalletCards size={13}/>} text={clean(job.salary)}/></div><div className="mt-6 flex items-center justify-between border-t border-[#edf0eb] pt-4"><span className="flex items-center gap-1.5 text-xs text-[#73847d]"><CalendarDays size={14}/>{when(job.date)}</span><button onClick={open} className="flex items-center gap-1 text-sm font-bold text-[#235b49]">Ver vaga <ArrowUpRight size={16}/></button></div></article>}
function Tag({icon,text}:{icon:React.ReactNode;text:string}){return <span className="flex max-w-full items-center gap-1.5 rounded-lg bg-[#f4f6f2] px-2.5 py-1.5"><span className="shrink-0">{icon}</span><span className="truncate">{text}</span></span>}
function Detail({job,close}:{job:Job;close:()=>void}){return <div className="fixed inset-0 z-50 bg-[#0d211a]/55 backdrop-blur-sm sm:grid sm:place-items-center sm:p-6" role="dialog" aria-modal="true"><article className="flex h-full w-full flex-col overflow-y-auto bg-[#f8f9f6] sm:h-auto sm:max-h-[90vh] sm:max-w-3xl sm:rounded-[2rem]"><div className="sticky top-0 flex items-center justify-between border-b border-[#e0e6df] bg-[#f8f9f6]/95 px-5 py-4"><button onClick={close} className="flex gap-2 text-sm font-semibold"><ArrowLeft size={17}/>Voltar às vagas</button><button onClick={close} aria-label="Fechar"><X/></button></div><div className="p-6 sm:p-9"><span className="rounded-full bg-[#e7f1c9] px-3 py-1 text-xs font-bold text-[#49611f]">Candidatura aberta</span><p className="mt-6 flex items-center gap-2 font-semibold text-[#4e6a60]"><Building2 size={18}/>{job.company}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{job.title}</h2><div className="mt-7 grid gap-3 sm:grid-cols-2"><Info l="Área" v={job.area}/><Info l="Nível" v={job.level}/><Info l="Modelo" v={job.model}/><Info l="Local" v={job.location}/><Info l="Salário" v={job.salary}/><Info l="Fonte" v={job.source}/></div><div className="mt-8 rounded-2xl border border-[#dce5dc] bg-white p-5"><h3 className="font-semibold">Sobre esta oportunidade</h3><p className="mt-2 text-sm leading-6 text-[#607269]">Esta vaga foi encontrada e verificada pela curadoria. Consulte a página original para ver a descrição completa, requisitos e condições.</p></div><a href={job.applyUrl} target="_blank" rel="noopener noreferrer" className="mt-7 flex w-full justify-center gap-2 rounded-2xl bg-[#173f35] px-6 py-4 font-bold text-white">Candidatar-se na página original <ArrowUpRight size={18}/></a></div></article></div>}
function Info({l,v}:{l:string;v:string}){return <div className="rounded-2xl border border-[#e0e6df] bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#7d8c85]">{l}</p><p className="mt-1 text-sm font-semibold">{clean(v)}</p></div>}

